my.email: tiendat.1392.hvact@gmail.com
my.password: Dat1392@

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/techjob
    username: root
    password: dat1392
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true